return {
  Absolute_Confidence = { cooldown = "None (Passive)", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/9/9b/Absolute_Confidence.png" },
  Aerodynamic_Slash = { cooldown = "40s/35s/30s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/2/21/Aerodynamic_Slash.png" },
  Blade_Trap = { cooldown = "25s/20s/15s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/e/e4/Blade_Trap.png" },
  Blink = { cooldown = "10s/8s/6s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/2/2b/Blink_new.png" },
  Bounty = { cooldown = "25s/20s", duration = "15s", image = "https://static.wikia.nocookie.net/bladeball/images/f/fd/Bounty_Ability.png" },
  Bunny_Leap = { cooldown = "8s/6s/4s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/0/08/Bunny_Leap.png" },
  Calming_Deflection = { cooldown = "20s/15s/10s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/b/bf/Calming_Deflection.png" },
  Chieftain_s_Totem = { cooldown = "35s/30s/25s", duration = "12s", image = "https://static.wikia.nocookie.net/bladeball/images/b/be/Chieftain%27s_Totem.png" },
  Continuity_Zero = { cooldown = "20s/15s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/8/82/Continuity_Zero.png" },
  Dash = { cooldown = "7s/6s/5s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/5/55/Dash.png" },
  Death_Slash = { cooldown = "15.5s/13s", duration = "3s/5s", image = "https://static.wikia.nocookie.net/bladeball/images/f/f5/DeathSlash.png" },
  Displace = { cooldown = "35s/30s/25s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/0/0f/Displace.png" },
  Doppelganger = { cooldown = "40s/35s", duration = "15s", image = "https://static.wikia.nocookie.net/bladeball/images/7/75/Doppelganger.png" },
  Dragon_Spirit = { cooldown = "28s/25s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/4/4b/Dragon_Spirit.png" },
  Dribble = { cooldown = "12s/10s/8s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/5/5b/Dribble.png" },
  Encrypted_Clone = { cooldown = "12s (full 27s)", duration = "15s", image = "https://static.wikia.nocookie.net/bladeball/images/4/40/Encrypted_Clone.png" },
  Flash_Counter = { cooldown = "20s/15s/10s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/3/3c/Flash_Counter.png" },
  Force = { cooldown = "40s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/8/87/Force.png" },
  Forcefield = { cooldown = "26s/22s/18s", duration = "5s/7s/9s", image = "https://static.wikia.nocookie.net/bladeball/images/0/0f/Forcefield.png" },
  Fracture = { cooldown = "20s/17s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/6/6c/Fracture.png" },
  Freeze = { cooldown = "30s/25s/20s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/0/00/Freeze.png" },
  Freeze_Trap = { cooldown = "35s/30s/25s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/c/c5/Freeze_Trap.png" },
  Gale_s_Edge = { cooldown = "30s/25s/20s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/2/24/Gale%27s_Edge.png" },
  Golden_Ball = { cooldown = "None (Passive)", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/0/05/Golden_Ball.png" },
  Guardian_Angel = { cooldown = "None (Passive)", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/a/a7/Guardian_Angel.png" },
  Hell_Hook = { cooldown = "25s/20s/15s", duration = "1.5s/2s/2.5s", image = "https://static.wikia.nocookie.net/bladeball/images/f/f7/Hell_Hook.png" },
  Infinity = { cooldown = "30s/25s", duration = "10s/12s", image = "https://static.wikia.nocookie.net/bladeball/images/e/e2/Infinity.png" },
  Invisibility = { cooldown = "20s/17s/14s", duration = "5s/7s/9s", image = "https://static.wikia.nocookie.net/bladeball/images/e/e5/Invisibility.png" },
  Luck = { cooldown = "None (Passive)", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/2/27/Luck_image.png" },
  Martyrdom = { cooldown = "45s/35s/25s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/f/ff/Martyrdom.png" },
  Misfortune = { cooldown = "35s/30s/25s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/4/4b/Misfortune.png" },
  Necromancer = { cooldown = "60s/50s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/5/5d/Necromancer.png" },
  Ninja_Dash = { cooldown = "10s/8s/6s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/b/b2/Ninja_Dash.png" },
  Phantom = { cooldown = "30s/25s", duration = "8s/10s", image = "https://static.wikia.nocookie.net/bladeball/images/e/ec/Phantom.png" },
  Phase_Bypass = { cooldown = "40s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/3/35/Phase_Bypass.png" },
  Platform = { cooldown = "15s/12s/9s", duration = "8s/10s/12s", image = "https://static.wikia.nocookie.net/bladeball/images/7/7d/Platform.png" },
  Pull = { cooldown = "30s/25s/20s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/3/31/Pull.png" },
  Pulse = { cooldown = "40s/35s/30s", duration = "5s/6s/7s", image = "https://static.wikia.nocookie.net/bladeball/images/9/9a/Pulse.png" },
  Qi_Charge = { cooldown = "25s/20s/15s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/f/f7/Qi-Charge.png" },
  Quad_Jump = { cooldown = "None (Passive)", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/b/b6/Quad_Jump.png" },
  Quantum_Arena = { cooldown = "1 Kill", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/c/c6/Quantum_Arena.png" },
  Quasar = { cooldown = "35s/30s/25s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/4/4e/Quasar.png" },
  Raging_Deflection = { cooldown = "35s/30s/25s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/4/46/Raging_Deflection.png" },
  Rapture = { cooldown = "30s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/e/e9/Rapture.png" },
  Reaper = { cooldown = "None (Passive)", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/6/6a/Reaper.png" },
  Scopophobia = { cooldown = "20s/15s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/c/c1/Scopophobia.png" },
  Serpent_Shadow_Clone = { cooldown = "40s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/8/85/Serpent_Shadow_Clone_image.png" },
  Shadow_Step = { cooldown = "26s/22.7s/19.5s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/d/d4/Shadow_Step.png" },
  Singularity = { cooldown = "25s/20s", duration = "Up to 5s", image = "https://static.wikia.nocookie.net/bladeball/images/d/d0/Singularity.png" },
  Slash_of_Duality = { cooldown = "30s/25s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/b/b2/Slash_of_Duality_V1.png" },
  Slashes_of_Fury = { cooldown = "30s/25s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/f/f9/Slashes_of_Fury_V1.png" },
  Super_Jump = { cooldown = "8s/7s/6s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/7/7f/Super_Jump.png" },
  Swap = { cooldown = "25s/19s/13s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/0/0d/Swap.png" },
  Tact = { cooldown = "None (Passive)", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/d/d0/Tact.png" },
  Telekinesis = { cooldown = "45s/38s/23s", duration = "few seconds", image = "https://static.wikia.nocookie.net/bladeball/images/c/c3/Telekinesis.png" },
  Thunder_Dash = { cooldown = "4s/3s/2s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/b/b4/Thunder_Dash.png" },
  Time_Hole = { cooldown = "35s/30s", duration = "8s/10s", image = "https://static.wikia.nocookie.net/bladeball/images/e/eb/Time_Hole.png" },
  Titan = { cooldown = "7s-60s", duration = "12s/infinite", image = "https://static.wikia.nocookie.net/bladeball/images/e/e6/Titan.png" },
  Tsunami = { cooldown = "N/A", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/9/94/Tsunami.png" },
  Virus = { cooldown = "None (Passive)", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/f/fd/Virus.png" },
  Waypoint = { cooldown = "3s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/c/c2/Waypoint.png" },
  Wind_Cloak = { cooldown = "30s/25s/20s", duration = 0, image = "https://static.wikia.nocookie.net/bladeball/images/6/69/Wind_Cloak.png" },
}
